defaults: &defaults
  working_directory: /home/circle/wealthsimple
  docker:
    - image: wealthsimple/node:9.11.1-docker
      environment:
        JUNIT_REPORT_PATH: /tmp/test-results
        JUNIT_REPORT_NAME: test-results.xml

references:
  attach_code_workspace: &attach_code_workspace
    attach_workspace:
      at: /home/circle/wealthsimple

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - *attach_code_workspace
      - run:
          name: Runs unit tests and linters
          command: yarn test
      - store_test_results:
          path: /tmp/test-results

  retirejs:
    <<: *defaults
    steps:
      - *attach_code_workspace
      - run:
          name: Checks code for known vulnerabilities
          command: yarn retire

  checkout:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-node-modules-{{ checksum "yarn.lock" }}
      - run:
          name: Checks out code and installs npm dependencies
          command: |
            yarn install --no-progress --cache-folder './.yarn-cache'
      - save_cache:
          key: v1-node-modules-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths: .

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout
      - retirejs:
          requires:
            - checkout
      - test:
          requires:
            - checkout

  security-audit:
    triggers:
      - schedule:
          # 11:35am UTC: 6:35am EST / 7:35am EDT
          cron: "35 11 * * *"
          filters:
            branches:
              only: master
    jobs:
      - checkout
      - retirejs:
          requires:
            - checkout
